on:
  schedule:
  - cron: '0 0 * * *'
name: Updates data
jobs:
  installDependencies:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install dependencies
      uses: actions/npm@59b64a598378f31e49cb76f27d6f3312b582f680
      with:
        args: install
    - name: Build partier
      uses: actions/npm@59b64a598378f31e49cb76f27d6f3312b582f680
      with:
        args: run build-partier
    - name: Build fylker
      uses: actions/npm@59b64a598378f31e49cb76f27d6f3312b582f680
      with:
        args: run build-fylker
    - name: Build direktorater
      uses: actions/npm@59b64a598378f31e49cb76f27d6f3312b582f680
      with:
        args: run build-direktorater
    - name: Build smartbyer
      uses: actions/npm@59b64a598378f31e49cb76f27d6f3312b582f680
      with:
        args: run build-smartbyer
    - name: Build NAV
      uses: actions/npm@59b64a598378f31e49cb76f27d6f3312b582f680
      with:
        args: run build-nav
    - name: Deploy to ZEIT
      env:
        ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }}
      run: now --prod --token ${ZEIT_TOKEN}
    - name: Commit changes
      uses: ./github-actions/commit-changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: Data updated (ignore)
