on:
  schedule:
  - cron: '0 0 * * *'
name: Updates data
jobs:
  installDependencies:
    name: Install dependencies and run build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: npm install
    - run: npm run build-partier
    - run: npm run build-fylker
    - run: npm run build-direktorater
    - run: npm run build-smartbyer
    - run: npm run build-nav
    - name: Deploy to ZEIT
      env:
        ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }}
      run: now --prod --token ${ZEIT_TOKEN} --confirm
    - name: Commit changes
      run: |
        git config --local user.email "geir.gasodden@pythonia.no"
        git config --local user.name "zrrrzzt"
        git commit -am "Updates data (ignore)"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
